export const URLS = {
	GEMINI_ORCHESTRATOR_API_URL:
		process.env.NEXT_PUBLIC_GEMINI_ORCHESTRATOR_API_URL!,
	GEMINI_DOCUMENT_API_URL: process.env.NEXT_PUBLIC_GEMINI_DOCUMENT_API_URL!,
	GEMINI_COMMON_URL: process.env.NEXT_PUBLIC_GEMINI_COMMON_URL!,
	AUTH_URL: process.env.NEXT_PUBLIC_AUTH_URL!,
} as const

export type URLS = typeof URLS
