export const RESPONSE_STATUS = {
	PLANNING: 'PLANNING',
	GENERATING_STRUCTURE: 'GENERATING_STRUCTURE',
	STRUCTURE_GENERATED: 'STRUCTURE_GENERATED',
	GENERATING_CONTENT: 'GENERATING_CONTENT',
	CONTENT_GENERATED: 'CONTENT_GENERATED',
	ENRICHING_REFERENCES: 'ENRICHING_REFERENCES',
	REFERENCES_ENRICHED: 'REFERENCES_ENRICHED',
	FORMATTING: 'FORMATTING',
	FORMATTED: 'FORMATTED',
	PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
	RECOVERY_FAILED: 'RECOVERY_FAILED',
	COMPLETED: 'COMPLETED',
	FAILED: 'FAILED',
} as const

export const STATUS_GROUPS = {
	RECOVERABLE: [
		RESPONSE_STATUS.PARTIALLY_COMPLETED,
		RESPONSE_STATUS.FAILED,
		RESPONSE_STATUS.RECOVERY_FAILED,
		RESPONSE_STATUS.GENERATING_CONTENT,
	],
	RETRY: [
		RESPONSE_STATUS.FAILED,
		RESPONSE_STATUS.RECOVERY_FAILED,
		RESPONSE_STATUS.PARTIALLY_COMPLETED,
		RESPONSE_STATUS.COMPLETED,
	],
	DONE: [RESPONSE_STATUS.COMPLETED],
} as const

export function statuses(status: string) {
	const isRecoverable = STATUS_GROUPS.RECOVERABLE.includes(
		status as (typeof STATUS_GROUPS.RECOVERABLE)[number]
	)
	const isCompleted = status === STATUS_GROUPS.DONE[0]
	const isGenerationWaiting =
		status === RESPONSE_STATUS.GENERATING_STRUCTURE ||
		(status !== RESPONSE_STATUS.COMPLETED && isRecoverable)

	const stopPollingStatuses = STATUS_GROUPS.RETRY
	return {
		isRecoverable,
		isCompleted,
		isGenerationWaiting,
		stopPollingStatuses,
	}
}
